#!/usr/bin/env bash

function release_service() {
    local service=$1
    local version=$(grep ^Version _oasis | sed 's/^.*: *\([^ ]\)/\1/')
    local release=$service-${version}
    make distclean
    rm ${release}.tar.gz
    ln -s . $release
    tar cvzf ${release}.tar.gz --exclude=${release}/${release} ${release}/*
    rm ${release}
    #git upload-release inhabitedtype ocaml-aws ${release} ${release}.tar.gz
    #rm ${release}.tar.gz
}

function release_top() {
    local version=$(grep Version _oasis | sed 's/^.*: *\([^ ]\)/\1/')
    local release=aws-${version}
    make distclean
    rm ${release}.tar.gz
    ln -s . $release
    tar cvzf ${release}.tar.gz --exclude=libraries/** --exclude=input/** --exclude=.git/** --exclude=${release}/${release} ${release}/*
    rm ${release}
    #git upload-release inhabitedtype ocaml-aws ${release} ${release}.tar.gz
    #rm ${release}.tar.gz
}

function release() {
    release_top
    for lib in $(ls libraries); do
        if [[ -d libraries/$lib ]]; then
            pushd libraries/$lib > /dev/null
            release_service $lib
            popd > /dev/null
        fi
    done
}

release
