#!/usr/bin/env bash

function release_service() {
    local service=$(oasis query name)
    local version=$(oasis query version)
    local release=$service-${version}
    echo "== $release"
    make distclean > /dev/null
    rm ${release}.tar.gz
    ln -s . $release
    tar czf ${release}.tar.gz --exclude=${release}/${release} ${release}/*
    rm ${release}
    if [[ -n ${COOKIE_JAR+x} ]]; then
        git upload-release -c ${COOKIE_JAR} inhabitedtype ocaml-aws ${aws_release} ${release}.tar.gz
    fi
}

function release_top() {
    local version=$(oasis query version)
    local release=aws-${version}
    echo "== $release"
    make distclean > /dev/null
    rm ${release}.tar.gz
    ln -s . $release
    tar czf ${release}.tar.gz --exclude=libraries/** --exclude=input/** --exclude=.git/** --exclude=${release}/${release} ${release}/*
    rm ${release}
    if [[ -n ${COOKIE_JAR+x} ]]; then
        git upload-release -c ${COOKIE_JAR} inhabitedtype ocaml-aws ${release} ${release}.tar.gz
    fi
}

function release() {
    release_top
    for lib in $(ls libraries); do
        if [[ -d libraries/$lib ]]; then
            pushd libraries/$lib > /dev/null
            release_service
            popd > /dev/null
        fi
    done
}

release
