#!/usr/bin/env bash
# Copyright (c) 2016 Inhabited Type LLC.
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the author nor the names of his contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE CONTRIBUTORS ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

AWS_RELEASE=aws-$(oasis query version)

function publish()
{
    local service=$(oasis query name)
    local version=$(oasis query version)
    local release=$service-${version}
    local uri="https://github.com/inhabitedtype/ocaml-aws/releases/download/$AWS_RELEASE/$release.tar.gz"
    echo "== $release"
    local dir=${release/-/.}
    mkdir -p $dir
    cp -r opam/* $dir
    rm $dir/findlib
    echo "archive:\"$uri\"" > $dir/url
    echo "checksum:\"$(curl -L $uri | md5)\"" >> $dir/url
    opam publish submit --name=seliopou $dir
}

function publish_libs() {
    for lib in $(ls libraries); do
        if [[ -d libraries/$lib ]]; then
            pushd libraries/$lib > /dev/null
            publish
            popd > /dev/null
        fi
    done
}

case $1 in
    "top") publish;;
    "libs") publish_libs;;
    *) echo "usage: publish [top|libs]"; exit 1;;
esac
