#!/usr/bin/env bash
# Copyright (c) 2016 Inhabited Type LLC.
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the author nor the names of his contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE CONTRIBUTORS ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

AWS_RELEASE=aws-$(oasis query version)

function release_service() {
    local service=$(oasis query name)
    local version=$(oasis query version)
    local release=$service-${version}
    local AWS_RELEASE=$1
    echo "== $release"
    make distclean > /dev/null
    rm -f *.tar.gz
    ln -s . $release
    tar czf ${release}.tar.gz --exclude=${release}/${release} ${release}/*
    rm ${release}
    if [[ -n ${COOKIE_JAR+x} ]]; then
        git upload-release -c ${COOKIE_JAR} inhabitedtype ocaml-aws ${AWS_RELEASE} ${release}.tar.gz
    fi
}

function release_top() {
    local version=$(oasis query version)
    local release=aws-${version}
    echo "== $release"
    make distclean > /dev/null
    rm -f *.tar.gz
    ln -s . $release
    tar czf ${release}.tar.gz --exclude=libraries/** --exclude=input/** --exclude=.git/** --exclude=${release}/${release} ${release}/*
    rm ${release}
    if [[ -n ${COOKIE_JAR+x} ]]; then
        git upload-release -c ${COOKIE_JAR} inhabitedtype ocaml-aws ${release} ${release}.tar.gz
    fi
}

function release_libs() {
    for lib in $(ls libraries); do
        if [[ -d libraries/$lib ]]; then
            pushd libraries/$lib > /dev/null
            release_service $AWS_RELEASE
            popd > /dev/null
        fi
    done
}

case $1 in
    "top") release_top;;
    "libs") release_libs;;
    "all") release_top; release_libs;;
    *) echo "usage: release [top|libs|all]"; exit 1;;
esac
